remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "What budget?"
description: "This application will help those who struggle with budgeting."
author:
  name: "Justin Kelly"
  